title: "TheMacroEdge"
description: "Global Financial Insights and Market Intelligence for 2026."
baseurl: "/TheMacroEdge" # ESTA ES LA LÍNEA CLAVE. Debe coincidir exacto con el nombre del repo
url: "https://themacroedge.online"
permalink: /:title/

url: "https://tu-usuario.github.io" # Cambia 'tu-usuario' por tu nombre real de GitHub
plugins:
  - jekyll-sitemap
